import os
import json
import base64
import urllib.parse
import urllib.request
import hashlib
import time
import hmac
import logging
from tornado import web
from jupyter_server.auth.identity import IdentityProvider, User

log = logging.getLogger("GitLabAuth")

GITLAB_URL = "https://gitlab.tugasakhir.space"
GITLAB_INTERNAL_URL = "http://gitlab.tugasakhir.space"
CLIENT_ID = "7106e57a32c43b8fb0d071d6120fad8f907a71a9da93b1df15e07c2078b9285b"
CLIENT_SECRET = "988656eb0229c26428c67b414d12376d8d51fa52ae6c29f1af43eadd85c8d31c"
REDIRECT_URI = "https://lab.tugasakhir.space/oauth_callback"
COOKIE_SECRET = "miniproject_gitlab_sso_secret_2026_salt_xyz99"

COLORS = [
    "var(--jp-collaborator-color1)",
    "var(--jp-collaborator-color2)",
    "var(--jp-collaborator-color3)",
    "var(--jp-collaborator-color4)",
    "var(--jp-collaborator-color5)",
    "var(--jp-collaborator-color6)",
    "var(--jp-collaborator-color7)"
]

def get_color_for_user(username):
    idx = int(hashlib.md5(username.encode()).hexdigest(), 16) % len(COLORS)
    return COLORS[idx]

def get_initials(name, username):
    parts = [p for p in name.replace('-', ' ').split() if p]
    if len(parts) >= 2:
        return (parts[0][0] + parts[-1][0]).upper()
    elif len(parts) == 1 and len(parts[0]) >= 2:
        return parts[0][:2].upper()
    return username[:2].upper()

def sign_data(data_dict):
    payload = json.dumps(data_dict)
    sig = hashlib.sha256((payload + COOKIE_SECRET).encode()).hexdigest()
    raw = f"{payload}:::{sig}"
    return base64.urlsafe_b64encode(raw.encode("utf-8")).decode("utf-8")

def verify_data(signed_b64):
    if not signed_b64:
        return None
    try:
        raw = base64.urlsafe_b64decode(signed_b64.encode("utf-8")).decode("utf-8")
        if ":::" not in raw:
            return None
        payload, sig = raw.rsplit(":::", 1)
        expected_sig = hashlib.sha256((payload + COOKIE_SECRET).encode()).hexdigest()
        if hmac.compare_digest(sig, expected_sig):
            return json.loads(payload)
    except Exception:
        pass
    return None

def save_user_git_profile(username, name, email, access_token, refresh_token=None, expires_in=7200):
    """Saves user credentials and updates active user profile for Git operations."""
    users_file = "/home/jovyan/.jupyter/gitlab_users.json"
    env_file = "/home/jovyan/.jupyter/user_env.sh"
    last_user_file = "/home/jovyan/.jupyter/last_active_user"

    try:
        os.makedirs(os.path.dirname(users_file), exist_ok=True)
        users_data = {"active_user": username, "users": {}}
        if os.path.exists(users_file):
            try:
                with open(users_file, "r") as f:
                    users_data = json.load(f)
            except Exception:
                users_data = {"active_user": username, "users": {}}

        users_data["active_user"] = username
        if "users" not in users_data:
            users_data["users"] = {}

        users_data["users"][username] = {
            "username": username,
            "name": name,
            "email": email,
            "token": access_token,
            "refresh_token": refresh_token,
            "expires_in": expires_in,
            "expires_at": time.time() + expires_in if expires_in else None,
            "last_login": time.time()
        }

        with open(users_file, "w") as f:
            json.dump(users_data, f, indent=2)

        with open(last_user_file, "w") as f:
            f.write(username)

        with open(env_file, "w") as f:
            f.write(f'''# Generated by JupyterLab GitLab SSO
export GIT_AUTHOR_NAME="{name}"
export GIT_AUTHOR_EMAIL="{email}"
export GIT_COMMITTER_NAME="{name}"
export GIT_COMMITTER_EMAIL="{email}"
export GITLAB_USER="{username}"
''')
    except Exception as e:
        log.error("Failed to save user git profile: %s", e)


class GitLabOAuthLoginHandler(web.RequestHandler):
    def get(self):
        auth_url = (
            f"{GITLAB_URL}/oauth/authorize?"
            + urllib.parse.urlencode({
                "client_id": CLIENT_ID,
                "redirect_uri": REDIRECT_URI,
                "response_type": "code",
                "scope": "read_user profile email openid api read_repository write_repository",
                "state": "jupyterlab_sso"
            })
        )
        self.redirect(auth_url)


class GitLabOAuthCallbackHandler(web.RequestHandler):
    def get(self):
        code = self.get_argument("code", None)
        if not code:
            self.set_status(400)
            self.write("Missing OAuth code from GitLab")
            return

        # Exchange code for access token via internal gateway
        token_url = f"{GITLAB_INTERNAL_URL}/oauth/token"
        data = urllib.parse.urlencode({
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
            "code": code,
            "grant_type": "authorization_code",
            "redirect_uri": REDIRECT_URI
        }).encode("utf-8")

        req = urllib.request.Request(
            token_url,
            data=data,
            headers={
                "Host": "gitlab.tugasakhir.space",
                "User-Agent": "JupyterLab-SSO"
            }
        )
        try:
            with urllib.request.urlopen(req, timeout=10) as response:
                token_resp = json.loads(response.read().decode("utf-8"))
        except Exception as e:
            self.set_status(500)
            self.write(f"Failed to exchange token with GitLab: {e}")
            return

        access_token = token_resp.get("access_token")
        refresh_token = token_resp.get("refresh_token")
        expires_in = token_resp.get("expires_in", 7200)

        if not access_token:
            self.set_status(500)
            self.write("No access_token returned by GitLab")
            return

        # Fetch user info from GitLab API
        user_url = f"{GITLAB_INTERNAL_URL}/api/v4/user"
        user_req = urllib.request.Request(
            user_url,
            headers={
                "Authorization": f"Bearer {access_token}",
                "Host": "gitlab.tugasakhir.space",
                "User-Agent": "JupyterLab-SSO"
            }
        )
        try:
            with urllib.request.urlopen(user_req, timeout=10) as resp:
                user_info = json.loads(resp.read().decode("utf-8"))
        except Exception as e:
            self.set_status(500)
            self.write(f"Failed to fetch user info from GitLab: {e}")
            return

        username = user_info.get("username", "guest")
        name = user_info.get("name", username)
        email = user_info.get("email", f"{username}@tugasakhir.space")
        avatar_url = user_info.get("avatar_url", "")
        initials = get_initials(name, username)
        color = get_color_for_user(username)

        # Save git profile & isolation mapping
        save_user_git_profile(username, name, email, access_token, refresh_token, expires_in)

        # Set Base64 URL-safe signed session cookie (valid 30 days)
        session_data = {
            "username": username,
            "name": name,
            "email": email,
            "initials": initials,
            "avatar_url": avatar_url,
            "color": color,
            "login_time": time.time()
        }
        signed_b64 = sign_data(session_data)
        self.set_cookie(
            "jupyter_user_session",
            signed_b64,
            expires_days=30,
            path="/",
            httponly=True,
            samesite="lax"
        )

        self.redirect("/lab")


class GitLabOAuthLogoutHandler(web.RequestHandler):
    def get(self):
        self.clear_cookie("jupyter_user_session", path="/")
        self.redirect("/oauth_login")


class GitLabIdentityProvider(IdentityProvider):
    login_handler_class = GitLabOAuthLoginHandler
    logout_handler_class = GitLabOAuthLogoutHandler
    def get_user(self, handler):
        cookie_val = handler.get_cookie("jupyter_user_session")
        if cookie_val:
            user_data = verify_data(cookie_val)
            if user_data:
                u_name = user_data.get("username", "user")
                full_name = user_data.get("name", u_name)
                return User(
                    username=u_name,
                    name=full_name,
                    display_name=f"{full_name} ({u_name})",
                    initials=user_data.get("initials", "U"),
                    avatar_url=user_data.get("avatar_url", ""),
                    color=user_data.get("color", "var(--jp-collaborator-color1)")
                )

        # Check if login request, static asset, or healthcheck
        req_path = getattr(handler.request, "path", "")
        if req_path.startswith(("/oauth_login", "/oauth_callback", "/oauth_logout", "/static", "/favicon", "/custom", "/api/status")):
            return User(username="anonymous", name="Anonymous", display_name="Anonymous", initials="A")

        # API token / MCP fallback
        token = handler.get_argument("token", None)
        auth_hdr = handler.request.headers.get("Authorization", "")
        if token == "miniproject2026" or "token miniproject2026" in auth_hdr:
            return User(
                username="rizkyyanuark",
                name="Rizky Yanuar Kristianto",
                display_name="Rizky Yanuar Kristianto (Admin)",
                initials="RYK",
                color="var(--jp-collaborator-color1)"
            )

        # Let super() handle other token / internal authentications
        try:
            user = super().get_user(handler)
            if user:
                return user
        except Exception:
            pass

        # Redirect unauthenticated browser GET requests to GitLab OAuth login
        accept_hdr = handler.request.headers.get("Accept", "")
        if "text/html" in accept_hdr and handler.request.method == "GET" and not req_path.startswith("/api"):
            handler.redirect("/oauth_login")
            return None

        return None


def _jupyter_server_extension_points():
    return [{"module": "gitlab_auth"}]


def _load_jupyter_server_extension(serverapp):
    handlers = [
        (r"/oauth_login", GitLabOAuthLoginHandler),
        (r"/oauth_callback", GitLabOAuthCallbackHandler),
        (r"/oauth_logout", GitLabOAuthLogoutHandler),
    ]
    serverapp.web_app.add_handlers(r".*", handlers)
    serverapp.log.info("✓ GitLab OAuth 2.0 SSO Extension successfully loaded!")
